### ISSUE TITLE
network.sh not in the package

### ISSUE THREAD

**Issue by haruanm** [Eloysheyin/Minimalist-Dots#1]
I'm trying to implement your beautiful theme and I've got some issues with fonts (I've installed material icons but it seems that you are using an old one), and the network.sh file is not in the repo, could you upload it please?

**Comment by haruanm** [comment]
I have just checked that the powermenu.sh is not on it too.

**Comment by Eloysheyin** [comment]
its inside .config/rofi/rofi menu

**Comment by haruanm** [comment]
Thanks, I was able to use them.
